spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 192.168.199.3
    port: 6379
    password: 11111111
    timeout: 5000
    # 连接池
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0